apiVersion: v1
kind: Pod
metadata:
  name: kubernetes_pod
  labels:
    app: kubernetestestapp
spec:
    containers:
        - name: kubernetes_test_app
          image: monojitdocker/kubernetestestapp:v1.0.2
          ports:
              - containerPort: 7007

        - name: mongo_server
          image: mongo
          imagePullPolicy: Always
          ports:
              - containerPort: 27017
        